FROM node:lts-bullseye

RUN npm install -g static-i18n \
    && npm install -g pug-cli \
    && npm install -g html-minifier \
    && npm install -g uglify-js \
    && npm install -g node-sass

WORKDIR /tmp